services:
  web:
    build: .
    ports:
      - "5173:5173"
    volumes:
    - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules: