import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
/* MUI */
import { Box, Button, Link } from "@mui/material";
import Grid from "@mui/material/Grid";
import Typography from "@mui/material/Typography";
const Footer = () => {
    return (_jsx(_Fragment, { children: _jsxs(Grid, { className: "bg-black text-white text-center mt-10", container: true, sx: { bgcolor: 'black', color: 'white', py: 3 }, children: [_jsxs(Grid, { item: true, xs: 12, sm: 6, md: 3, children: [_jsx(Typography, { className: 'pb-5', variant: 'h6', children: "Company" }), _jsx(Box, { children: _jsx(Button, { className: 'pb-5', children: "About" }) }), _jsx(Box, { children: _jsx(Button, { className: 'pb-5', children: "Blog" }) }), _jsx(Box, { children: _jsx(Button, { className: 'pb-5', children: "Press" }) }), _jsx(Box, { children: _jsx(Button, { className: 'pb-5', children: "Jobs" }) }), _jsx(Box, { children: _jsx(Button, { className: 'pb-5', children: "Partners" }) })] }), _jsxs(Grid, { item: true, xs: 12, sm: 6, md: 3, children: [_jsx(Typography, { className: 'pb-5', variant: 'h6', children: "Solutions" }), _jsx(Box, { children: _jsx(Button, { className: 'pb-5', children: "Marketing" }) }), _jsx(Box, { children: _jsx(Button, { className: 'pb-5', children: "Analytics" }) }), _jsx(Box, { children: _jsx(Button, { className: 'pb-5', children: "Commerce" }) }), _jsx(Box, { children: _jsx(Button, { className: 'pb-5', children: "Insights" }) }), _jsx(Box, { children: _jsx(Button, { className: 'pb-5', children: "Support" }) })] }), _jsxs(Grid, { item: true, xs: 12, sm: 6, md: 3, children: [_jsx(Typography, { className: 'pb-5', variant: 'h6', children: "Documentation" }), _jsx(Box, { children: _jsx(Button, { className: 'pb-5', variant: "text", children: "Guides" }) }), _jsx(Box, { children: _jsx(Button, { className: 'pb-5', variant: "text", children: "Api Status" }) })] }), _jsxs(Grid, { item: true, xs: 12, sm: 6, md: 3, children: [_jsx(Typography, { className: 'pb-5', variant: 'h6', children: "Legal" }), _jsx(Box, { children: _jsx(Button, { className: 'pb-5', variant: "text", children: "Claim" }) }), _jsx(Box, { children: _jsx(Button, { className: 'pb-5', variant: "text", children: "Privacy" }) }), _jsx(Box, { children: _jsx(Button, { className: 'pb-5', variant: "text", children: "Terms" }) })] }), _jsxs(Grid, { className: "pt-20", item: true, xs: 12, children: [_jsx(Typography, { variant: "body2", component: "p", align: "center", children: "\u00A9 2023 My Company. All rights reserved." }), _jsx(Typography, { variant: "body2", component: "p", align: "center", children: "Made with love by Me." }), _jsxs(Typography, { variant: "body2", component: "p", align: "center", children: ["Icons made by", ' ', _jsx(Link, { href: "https://www.freepik.com", color: "inherit", underline: "always", children: "Freepik" }), ' ', "from(' ')", _jsx(Link, { href: "https://www.flaticon.com/", color: "inherit", underline: "always", children: "www.flaticon.com" }), " "] })] })] }) }));
};
export default Footer;
