export const  FIND_PRODUCT_BY_ID_REQUEST =  "FIND_PRODUCT_BY_ID_REQUEST";
export const  FIND_PRODUCT_BY_ID_SUCCESS =  "FIND_PRODUCT_BY_ID_SUCCESS";
export const  FIND_PRODUCT_BY_ID_FAILURE =  "FIND_PRODUCT_BY_ID_FAILURE";

export const  FIND_PRODUCT_BY_FURNITURE_REQUEST =  "FIND_PRODUCT_BY_FURNITURE_REQUEST";
export const  FIND_PRODUCT_BY_FURNITURE_SUCCESS =  "FIND_PRODUCT_BY_FURNITURE_SUCCESS";
export const  FIND_PRODUCT_BY_FURNITURE_FAILURE =  "FIND_PRODUCT_BY_FURNITURE_FAILURE";

export const  FIND_PRODUCT_BY_BRANDS_REQUEST =  "FIND_PRODUCT_BY_BRANDS_REQUEST";
export const  FIND_PRODUCT_BY_BRANDS_SUCCESS =  "FIND_PRODUCT_BY_BRANDS_SUCCESS";
export const  FIND_PRODUCT_BY_BRANDS_FAILURE =  "FIND_PRODUCT_BY_BRANDS_FAILURE";

export const  FIND_PRODUCT_BY_DECORATION_REQUEST =  "FIND_PRODUCT_BY_DECORATION_REQUEST";
export const  FIND_PRODUCT_BY_DECORATION_SUCCESS =  "FIND_PRODUCT_BY_DECORATION_SUCCESS";
export const  FIND_PRODUCT_BY_DECORATION_FAILURE =  "FIND_PRODUCT_BY_DECORATION_FAILURE";

export const  FIND_PRODUCTS_REQUEST =  "FIND_PRODUCTS_REQUEST";
export const  FIND_PRODUCTS_SUCCESS =  "FIND_PRODUCTS_SUCCESS";
export const  FIND_PRODUCTS_FAILURE =  "FIND_PRODUCTS_FAILURE";

export const  DELETE_PRODUCT_REQUEST =  "DELETE_PRODUCT_REQUEST";
export const  DELETE_PRODUCT_SUCCESS =  "DELETE_PRODUCT_SUCCESS";
export const  DELETE_PRODUCT_FAILURE =  "DELETE_PRODUCT_FAILURE";

export const  CREATE_PRODUCT_REQUEST =  "CREATE_PRODUCT_REQUEST";
export const  CREATE_PRODUCT_SUCCESS =  "CREATE_PRODUCT_SUCCESS";
export const  CREATE_PRODUCT_FAILURE =  "CREATE_PRODUCT_FAILURE";